### ISSUE TITLE
Issues from walk through with Alison

### ISSUE THREAD

**Issue by mgrauer** [DigitalSlideArchive/DSA-WSI-DeID#111]
This should probably be reprocessed into more specific issues:

- add red boxes to click targets, or some other indication of click targets, in screenshots in usage
- add table of contents
- add horizontal lines between sections
- make it more clear how to click on item name from folder view
- tell users to use chrome, not edge
- hide metadata detail menu
- screenshot with here are the things you need to look at and ignore, b/c shouldn't look at annotations or metadata
- update the label/redaction process, when first available to process, it will show that it will be wiped clean, so always will be label removed
- possibly a link to usage docs or workflow diagram, and display that in the UI, or display 'step 3' somewhere in UI for a given folder state, maybe workflow display in a modal?
- maybe have documentation follow workflow diagram (step 1 in diagram, step 1 in text)
- export docs as a pdf, with version stamp

**Comment by manthey** [comment]
I think these were all adequately addressed.
