### ISSUE TITLE
Aperio GT 450 SVS file macro image not getting redacted

### ISSUE THREAD

**Issue by fiendish** [DigitalSlideArchive/DSA-WSI-DeID#190]
~Looking for "label" and "macro" strings would break on those images. Instead remove IFDs with TIFF_SUBFILETYPEs  1 and 9 instead (the real images will be type 0).~

Nothing I do causes the macro image to get redacted in the below linked file.

**Comment by manthey** [comment]
@fiendish Are you sure this is a problem?  There is code to fall back to the SubfileType if the ImageDescription doesn't contain the associated image key.  If so, can you provide a sample file?

**Comment by fiendish** [comment]
Try redacting the macro image from (warning large download) https://slides.cldavis.org/slides/slideupload/NEVPC2020_8.svs

**Comment by fiendish** [comment]
Ah, you're right but...

I tried redacting the macro image from (warning 1.3GB download) (also warning, this is not my file) https://slides.cldavis.org/slides/slideupload/NEVPC2020_8.svs and it didn't work for me and the macro image remained. Maybe I did something wrong in my testing, but I went and looked inside process.py and saw that you're internally using openslide which has an open bug report regarding identification of label and macro images so I was wondering if perhaps the macro image string isn't getting into my image redaction list despite your local key setting.
