### ISSUE TITLE
No matching route for GET /adjancent_images/

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/DSA-WSI-DeID#196]
When loading an item with multiple images, the client makes a call to an API endpoint, `GET /adjacent_images/`. However, this endpoint is not implemented yet.

This doesn't appear to break any workflows, but the next/previous buttons above an image don't seem to work. 

This issue was found running a local copy of the master branch, and going through basic workflows with the test data.

**Comment by manthey** [comment]
The adjacent_images endpoint is added by the HistomicsUI plugin.  What version of the HistomicsUI plugin is installed?

**Comment by naglepuff** [comment]
I believe 1.0.0 is the version that I have installed.

**Comment by manthey** [comment]
I removed the `--pre` flag from the pip installation in the Dockerfile as I (erroneously) thought all packages we depend on had new enough official releases.  I've made PR #197 to ensure we have an adequate version of HistomicsUI.
