### ISSUE TITLE
Edit metadata values

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#201]
Instead of redacting metadata, allow it to be changed when appropriate

**Comment by manthey** [comment]
This will be another boolean setting to enable editing.  When enabled, controls with a Redact button/dropdown can also have a replacement text field that will appear IF redacting has been selected.  The back end should already support this, so it should just be a matter of adding the value from the text field.

**Comment by manthey** [comment]
We currently automatically assign some replacement values on import (e.g., the filename gets assigned to aperio.Filename and aperio.Title, and some dates get modified).  We might need to add some indicator if the new value was auto-assigned or user edited.  Maybe this is a new (possibly not listed in the drop down) redaction reason.

**Comment by naglepuff** [comment]
Should editing metadata be on or off by default?

**Comment by manthey** [comment]
Off.
