### ISSUE TITLE
More information from the Upload file

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#202]
Ingestion of primary tumor data fields (ICD-O topography code and label, ICD-O morphology code and preferred histology term, and ICD-O behavior code) from the DeID Upload File.

This should be a modification of the schema.

**Comment by naglepuff** [comment]
It looks like we already ingest the ICD-O topography code as `Spec_Site`. Would this change just require adding a field for the ICD-O Morphology codes and ICD-O behavior codes?

Would the format follow the example of `Spec_Site`, where each field should be an enum with the format 
`<code>-<description>`?

**Comment by manthey** [comment]
Fundamentally, the primary task here is to make sure we document how to change the schema and provide an example doing so.  I was sent a sample excel file that had columns `Tumor_Rec_Number`, `Histology_Code`, and `Behavior_Code` where some sample values where `01`, `9440`, `3` respectively.  For the nonce, if we show adding those fields with a regex (2, 4, 1 digit respectively?), and removing `Spec_Site` or making it optional, just as an alternative schema, that would be sufficient.

**Comment by manthey** [comment]
Our current goal is to show that what we have can be modified to be more sophisticated or precise when needed.  Probably this task is just the sample alternative schema and documentation.  Adding in the making a setting for exported fields (#237) would complete the requirements for now.
