### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#204]
Text/character recognition on label and slide images within WSI file 
- [x] Transfer of WSIs that do not have recognizable text/character recognition on label or slide images within WSI file to a folder for manual review.
- [ ] Permit user to manually review and redact the WSI files that do not have recognizable text/characters

**Comment by naglepuff** [comment]
Is OCR something that should be incorporated into the import process? 

If recognizable text is found on labels/slides, should those images be redacted automatically, and the WSI sent to an existing folder, such as `Redacted`? 

Or is this separate in some way from the existing workflows?

**Comment by manthey** [comment]
We will want to run OCR on import (and also have a way to do it afterwards to make it easier to use in other workflows).  We shouldn't redact automatically -- the OCR text will get added to the metadata and probably be used to correspond the WSI file with additional information, and, I think, auto-renaming it.  We'll learn more when we have some examples from the project.

**Comment by manthey** [comment]
The remainder of this is its own issue (#252), so closing this.
