### ISSUE TITLE
Assign metadata based on PII file and label data

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#205]
Automatic assignment of metadata based on imported subject personally identifiable information (PII file) (name, date of birth, etc.) and text interpretation on label portion of slide image 
1.	Transfer of WSIs that do not match the PII in the uploaded PII file to a sequestered folder for further manual review by user
2.	Notification window to user with information about the WSIs that do not match the PII in the uploaded file
3.	Permit user to manually review and redact the sequestered WSIs that did not match the PII in the uploaded PII fil

**Comment by manthey** [comment]
This issue relies on #204 and #202.

Specifically, we need to document how to use a different schema file (document as part of #206), and mention that if the schema does not require an `InputFileName` field, that metadata will be associated from OCR data and the remaining data in the input file.  We may want to make the name of the column `InputFileName` configurable for flexibility, and we may want to make the output configurable (#237) while working on this.

We need to define another project folder (much like AvailableToProcess, Redacted, etc.).  For now, call it "Unfiled".

On import, if the schema does not have `InputFileName`, we should import all files that we find and place them in Unfiled.  Then, when OCR results are finished (still add them to the metadata), we would check if there are words in the OCR that uniquely match some fields in a single row of the latest upload file.  We'll need to store the upload file data somewhere (perhaps with the OCR job). If these match, the file would then be given a name from the upload file (e.g., from the ImageID field or another configurable base field (e.g, TokenID) which could then optionally be suffixed with a unique value). Once renamed, the file would be moved into the AvailbleToProcess folder and be processed as before.

**Comment by naglepuff** [comment]
For schema changes, is it a binary between having an `InputFileName` column and not having that column?

Are we going to support a use case where `InputFileName` is in the schema, but some rows in the import sheet don't have a value in that column? I guess in that case, after importing all of the files with names in the import sheet, the other files in the import directory would be sent to the "Unfiled" directory, and then the system would proceed with the OCR steps, trying to match those files to rows in the import spreadsheet with no value in that column. Is this a scenario that we're anticipating?

**Comment by manthey** [comment]
Our current requests are for it to be binary, but the schema itself can specify if the field is required to be populated or not, so it probably makes sense to say if the import file passes validation, then only use Unfiled and OCR on files that don't have it set.  Specifically, if the Unfiled directory is NOT set, then we could use the current behavior of reporting an error for files without an associated InputFileName in the input directory, whereas if it is set, then unlisted files would got to Unfiled.  Any row of the input with InputFileName set shouldn't be a candidate for matching OCR (but maybe it should be kept to ensure uniqueness of matching exactly one row).

**Comment by naglepuff** [comment]
> Our current requests are for it to be binary, but the schema itself can specify if the field is required to be populated or not, so it probably makes sense to say if the import file passes validation, then only use Unfiled and OCR on files that don't have it set. 

It seems like we could accomplish this by only changing the `required` property of the existing schema such that `InputFileName` is no longer required. That way, either import file would be considered "valid." 

> Specifically, if the Unfiled directory is NOT set, then we could use the current behavior of reporting an error for files without an associated InputFileName in the input directory, whereas if it is set, then unlisted files would got to Unfiled. Any row of the input with InputFileName set shouldn't be a candidate for matching OCR (but maybe it should be kept to ensure uniqueness of matching exactly one row).

So would the Unfiled directory not be provisioned with the others in the WSI DeID collection? When would that be set?

**Comment by manthey** [comment]
I suppose we could have an option in the settings; the provision file can read the settings (since it imports Girder), and provision or unprovision the Unfiled directory based on that.

**Comment by manthey** [comment]
Added in #250.
