### ISSUE TITLE
Add reason for rejection

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#286]
Optionally have a reason for rejecting slides:
![image](https://user-images.githubusercontent.com/8781639/189720700-6b9cf398-b239-4a35-b868-56b05cb9fc51.png)

**Comment by manthey** [comment]
This would also have "cannot redact PHI"

**Comment by manthey** [comment]
Alison says remove "oil" from this list and add "cover slip issues" and "other" per category.

**Comment by naglepuff** [comment]
To clarify, would the default option for such a drop down be "Keep (Do no redact)?"

In that case would the Reject button be disabled by default, and the user would be forced to pick an option before rejection?

**Comment by naglepuff** [comment]
Reasons for rejection should be configurable
