### ISSUE TITLE
Batch process unfiled images

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#289]
Assign the images a randomized non-PII identifier.  The identifier "needs to be alphanumeric and randomly generated" with a structure specified by a configuration parameter.

We may want to have an option to assign a selected list of images to a single case or have all images be separate cases (e.g., do all selected images end up in the same folder or in separate folders).

**Comment by naglepuff** [comment]
Is batch assignment to an existing case something that should be supported from the get-go? 

If so, what would be best way to obtain all eligible cases for the selected images? I see the `/refileList` endpoint, but it requires an item ID. Can the valid list of valid cases differ from item to item? Is it based on the import spec? Would we need to call the endpoint several times to get all valid cases?

**Comment by manthey** [comment]
We don't have to assigned to an existing case initially, but we will want to just so it can be done from the folder level.

The reason refileList endpoint takes an item id is that when we import we record what was in the manifest file(s) and if a second import was done, some images could have different manifest data than other.

Probably the thing to do from a folder perspective is to create a folder endpoint for refileList and take the intersection of available values.  In the immediate term, we could call refileList for an arbitrary item in the folder, but making a folder-level endpoint should be quick.

**Comment by manthey** [comment]
@naglepuff See https://github.com/DigitalSlideArchive/DSA-WSI-DeID/pull/302 for a folder `refileList` endpoint.
