### ISSUE TITLE
Make PHI/PII Types Configurable

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/DSA-WSI-DeID#319]
The PHI definitions and types are listed [here in the usage documentation](https://github.com/DigitalSlideArchive/DSA-WSI-DeID/blob/master/docs/USAGE.rst#phipii-definitions-and-types). They are defined in [utils.js](https://github.com/DigitalSlideArchive/DSA-WSI-DeID/blob/5e01ba05a5b295f29a2ee29debe4f1c6f2ed06aa/wsi_deid/web_client/utils.js#L15).

As per internal discussion, these should be configurable via setting. To accomplish this, I think the following should be done:

- [x] Support a new setting in the girder config: `phi_pii_types`
- [x] Add a default value containing all of the values currently present in the usage docs to the `defaultConfig` dictionary in `config.py`
- [x] Remove the value from `utils.js`, and get the information from the `settings` object instead (populated by API call)
- [x] Update customization documentation to include the ability to configure PHI/PII types

**Comment by naglepuff** [comment]
@manthey Does this seem like a sane approach?

**Comment by manthey** [comment]
> @manthey Does this seem like a sane approach?

Yes, sounds perfect.
