### ISSUE TITLE
Checkboxes in lists on update

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#342]
If you check a list of items, and then that list refreshes to show the list with metadata, the checkboxes become unchecked and then don't behave as expected.  Either disable the action buttons OR preserve the checkmarks during the update.

**Comment by manthey** [comment]
@naglepuff Would you have time to try to address this?

**Comment by naglepuff** [comment]
I'll take a look

**Comment by naglepuff** [comment]
@manthey what would cause a list to get refreshed in this way? On load, I see the item list get loaded, and then another render which adds all of the metadata columns. Would someone have to check items in between these two steps or is there another way to observe the behavior?

**Comment by manthey** [comment]
The project item list pages get rendered twice; once in the default Girder list mode and then when enough information is loaded again in the project specific mode.  If you click the "check all" box after the first render and before the second render, the check all box is checked BUT no specific item is checked.  If you then click a processing task (e.g., redact), it fails because the button is improperly enabled (either nothing should be selected and the button disabled, or something should still be selected).
