### ISSUE TITLE
mongo:latest keeps crashing and I can't tell why

### ISSUE THREAD

**Issue by markemus** [DigitalSlideArchive/DSA-WSI-DeID#345]
Hey, I'm trying to set this up using the docker-compose approach described [here](https://github.com/DigitalSlideArchive/DSA-WSI-DeID/blob/master/docs/INSTALL.rst#import-and-export-paths) with import and export paths. I've tried it on my laptop and in a VM on a server, and in both cases I'm getting different errors. On the laptop it says that:
```

mongodb_1    | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongodb_1    |   see https://jira.mongodb.org/browse/SERVER-54407
mongodb_1    |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongodb_1    |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
```
On the server I get a big json printout that repeats endlessly, I can't tell what it is.

Have you guys seen these errors before or do you know what I'm doing wrong? Is there a version of mongodb I can use to at least get it working on the laptop?

**Comment by manthey** [comment]
The error you posted tells why -- Mongo 5.x and greater require AVX support.  Some VMs don't expose this, even though pretty much all modern processors have it.  The two solutions are to either pin to Mongo 4.4 OR enable AVX support passthrough on the VM.  I don't know why Mongo chose to compile and ship without the appropriate fallback code, and I'm not sure how we can show a better error message when this occurs.

**Comment by markemus** [comment]
Thanks that fixed it in both.

**Comment by manthey** [comment]
Closing.  Though if you know a way to have docker-compose detect this before starting contains so we can give a better warning, I'd love to know how.
