### ISSUE TITLE
Harmonize usage docs

### ISSUE THREAD

**Issue by mgrauer** [DigitalSlideArchive/DSA-WSI-DeID#59]
Make a pass for consistency such as:

- primacy of Folders vs States
- usage of colons and quotes
- usage of bullet points
- usage of ``backtick quoted material``

**Comment by mgrauer** [comment]
capitalization

**Comment by manthey** [comment]
@naglepuff Would you care to do a read-through of the docs and see if any of these need adjusting?  If so, please make a PR.  If not, please close this issue.

**Comment by naglepuff** [comment]
Sure, will do.
