### ISSUE TITLE
Consider removing or hiding certain elements of the UI

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/DSA-WSI-DeID#64]
Should we start with the Girder metadata section collapsed?  This is a straightforward as adding `data-toggle="collapse" data-target=".g-widget-metadata-container:first"` to the `.g-widget-metadata-header` item and adding the `collapse` class to the metadata container (of `collapse in` classes to start expanded).

We could also remove the Annotations block, as we don't expect to be using them for this project.

**Comment by mgrauer** [comment]
I agree with both ideas, especially if easy.

**Comment by cooperlab** [comment]
I haven't been involved much in this but I think @dgutman mentioned that there are future plans for annotation.

Definitely these should be collapsed by default because that's a lot of screen real estate.
